name: Build project

on:
  pull_request: {}
  push: { branches: [main] }
  workflow_dispatch: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  UNITY_VERSION: 2019.4.12f1
  PROJECT_PATH: TestProject
  ITCH_GAME: test
  ITCH_USER: gabrielvidal

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
#          - StandaloneWindows # Build a Windows standalone.
#          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - iOS # Build an iOS player.
#          - Android # Build an Android .apk standalone app.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.PROJECT_PATH }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ env.PROJECT_PATH }}-
            Library-
      - uses: webbertakken/unity-builder@v2.0-alpha-1
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
#      - uses: josephbmanley/butler-publish-itchio-action@master
#        env:
#          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
#          CHANNEL: windows
#          ITCH_GAME: ${{ env.ITCH_GAME }}
#          ITCH_USER: ${{ env.ITCH_USER }}
#          PACKAGE: build
